use std::fmt;

#[derive(Clone, Copy, Debug, Deserialize, Eq, Ord, PartialEq, PartialOrd, Serialize)]
pub enum LanguageName {
    ActionScript,
    Assembly,
    Bash,
    Batch,
    C,
    CHeader,
    Clojure,
    CoffeeScript,
    ColdFusion,
    ColdFusionScript,
    Coq,
    Cpp,
    CppHeader,
    CSharp,
    CShell,
    Css,
    D,
    Dart,
    DeviceTree,
    Erlang,
    FortranLegacy,
    FortranModern,
    Go,
    Haskell,
    Html,
    Idris,
    Jai,
    Java,
    JavaScript,
    Julia,
    Json,
    Jsx,
    Kotlin,
    Less,
    LinkerScript,
    Lisp,
    Lua,
    Makefile,
    Markdown,
    Mustache,
    Nim,
    ObjectiveC,
    ObjectiveCpp,
    OCaml,
    Oz,
    Pascal,
    Perl,
    Polly,
    Php,
    Protobuf,
    Prolog,
    Python,
    Qcl,
    R,
    Ruby,
    RubyHtml,
    Rust,
    Sass,
    Scala,
    Sml,
    Sql,
    Swift,
    Tex,
    Text,
    Toml,
    TypeScript,
    VimScript,
    UnrealScript,
    Wolfram,
    Xml,
    Yaml,
    Zsh,
    __Total,
}

impl LanguageName {
    pub fn name(&self) -> &'static str {
        use self::LanguageName::*;

        match *self {
            ActionScript => "ActionScript",
            Assembly => "Assembly",
            Bash => "BASH",
            Batch => "Batch",
            C => "C",
            CHeader => "C Header",
            Clojure => "Clojure",
            CoffeeScript => "CoffeeScript",
            ColdFusion => "ColdFusion",
            ColdFusionScript => "ColdFusion CFScript",
            Coq => "Coq",
            Cpp => "C++",
            CppHeader => "C++ Header",
            CSharp => "C#",
            CShell => "C Shell",
            Css => "CSS",
            D => "D",
            Dart => "Dart",
            DeviceTree => "Device Tree",
            Erlang => "Erlang",
            FortranLegacy => "FORTRAN Legacy",
            FortranModern => "FORTRAN Modern",
            Go => "Go",
            Haskell => "Haskell",
            Html => "HTML",
            Idris => "Idris",
            Jai => "JAI",
            Java => "Java",
            JavaScript => "JavaScript",
            Json => "JSON",
            Jsx => "JSX",
            Julia => "Julia",
            Kotlin => "Kotlin",
            Less => "LESS",
            LinkerScript => "LD Script",
            Lisp => "LISP",
            Lua => "Lua",
            Makefile => "Makefile",
            Markdown => "Markdown",
            Mustache => "Mustache",
            Nim => "Nim",
            ObjectiveC => "Objective C",
            ObjectiveCpp => "Objective C++",
            OCaml => "OCaml",
            Oz => "Oz",
            Pascal => "Pascal",
            Perl => "Perl",
            Polly => "Polly",
            Php => "PHP",
            Protobuf => "Protocol Buffers",
            Prolog => "Prolog",
            Python => "Python",
            Qcl => "QCL",
            R => "R",
            Ruby => "Ruby",
            RubyHtml => "Ruby HTML",
            Rust => "Rust",
            Sass => "Sass",
            Scala => "Scala",
            Sml => "Standard ML",
            Sql => "SQL",
            Swift => "Swift",
            Tex => "TeX",
            Text => "Plain Text",
            Toml => "TOML",
            TypeScript => "TypeScript",
            UnrealScript => "Unreal Script",
            VimScript => "Vim Script",
            Wolfram => "Wolfram",
            Xml => "XML",
            Yaml => "YAML",
            Zsh => "Zsh",
            __Total => "Total",
        }
    }
}

impl fmt::Display for LanguageName {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}", self.name())
    }
}
